<?php

/*
|--------------------------------------------------------------------------
| RDA (Resource Description and Access) controlled vocabularies
|--------------------------------------------------------------------------
|
| Lists taken from the legacy myRDA+PLUS reference files (media.txt,
| carrier.txt, content.txt, Language.txt, location.txt, library.txt,
| genre.txt, Notes.txt). Edit freely to add or remove choices.
|
*/

return [

    'media_types' => [
        'audio',
        'computer',
        'microform',
        'microscopic',
        'projected',
        'stereographic',
        'unmediated',
        'video',
        'other',
        'unspecified',
    ],

    'carrier_types' => [
        'audio cartridge',
        'audio cylinder',
        'audio disc',
        'aperture card',
        'audio roll',
        'audiocassette',
        'audiotape reel',
        'card',
        'computer card',
        'computer chip cartridge',
        'computer disc',
        'computer disc cartridge',
        'computer tape cartridge',
        'computer tape cassette',
        'computer tape reel',
        'film cartridge',
        'film cassette',
        'film reel',
        'film roll',
        'filmslip',
        'filmstrip',
        'filmstrip cartridge',
        'flipchart',
        'microfiche',
        'microfiche cassette',
        'microfilm cartridge',
        'microfilm cassette',
        'microfilm reel',
        'microfilm roll',
        'microfilm slip',
        'microopaque',
        'microscope slide',
        'object',
        'online resource',
        'overhead transparency',
        'roll',
        'slide',
        'sheet',
        'sound track reel',
        'stereograph card',
        'stereograph disc',
        'volume',
        'video cartridge',
        'videocassette',
        'videodisc',
        'videotape reel',
        'unspecified',
    ],

    'content_types' => [
        'cartographic dataset',
        'cartographic image',
        'cartographic moving image',
        'cartographic tactile image',
        'cartographic tactile three-dimensional form',
        'cartographic three-dimensional form',
        'computer dataset',
        'computer program',
        'notated movement',
        'notated music',
        'performed music',
        'sounds',
        'spoken word',
        'still image',
        'tactile image',
        'tactile notated music',
        'tactile notated movement',
        'tactile text',
        'tactile  three-dimensional form',
        'text',
        'three-dimensional form',
        'three-dimensional moving image',
        'two-dimensional moving image',
        'other',
        'unspecified',
    ],

    'languages' => [
        'Bahasa',
        'Chinese',
        'English',
        'Filipino',
        'French',
        'German',
        'Greek',
        'Hebrew',
        'Italian',
        'Korean',
        'Latin',
        'Mandarin',
        'Nippongo',
        'Spanish',
        'Tagalog',
        'Taglish',
        'Vernacular',
    ],

    'locations' => [
        'Circulation',
        'Filipiniana',
        'General reference',
        'Reserve',
        'Rizaliana',
        'Special collection',
    ],

    'libraries' => [
        'All libraries',
        'College Library',
        'High School Library',
        'Grade School Library',
    ],

    'genres' => [
        'abstract or summary',
        'art original',
        'art reproduction',
        'article',
        'atlas',
        'autobiography',
        'bibliography',
        'biography',
        'book',
        'calendar',
        'catalog',
        'chart',
        'comic or graphic novel',
        'comic strip',
        'conference publication',
        'database',
        'dictionary',
        'diorama',
        'directory',
        'discography',
        'drama',
        'encyclopedia',
        'essay',
        'festschrift',
        'fiction',
        'filmography',
        'filmstrip',
        'finding aid',
        'flash card',
        'folktale',
        'font',
        'game',
        'government publication',
        'graphic',
        'globe',
        'handbook',
        'history',
        'hymnal',
        'humor, satire',
        'index',
        'instruction',
        'interview',
        'issue',
        'journal',
        'kit',
        'language instruction',
        'law report or digest',
        'legal article',
        'legal case and case notes',
        'legislation',
        'letter',
        'loose-leaf',
        'map',
        'memoir',
        'microscope slide',
        'model',
        'motion picture',
        'multivolume monograph',
        'newspaper',
        'novel',
        'numeric data',
        'offprint',
        'online system or service',
        'patent',
        'periodical',
        'picture',
        'poetry',
        'programmed text',
        'realia',
        'rehearsal',
        'remote sensing image',
        'reporting',
        'review',
        'script',
        'series',
        'short story',
        'slide',
        'sound',
        'speech',
        'standard or specification',
        'statistics',
        'survey of literature',
        'technical drawing',
        'technical report',
        'thesis',
        'toy',
        'transparency',
        'treaty',
        'videorecording',
        'web site',
        'yearbook',
    ],

    'notes' => [
        'Includes index',
        'Includes bibliographic references',
        'Includes bibliographic references and index',
        'Includes bibliography',
    ],

];
